import Head from "next/head"

export const Header = () => {
  return (
    <Head>
      <title>Navneet Kumar</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/N.png" />
    </Head>
  )
}
